# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MerryExamples' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MerryExamples

  target 'MerryExamples-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MerryExamplesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MerryExamples-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MerryExamples-tvOS

  target 'MerryExamples-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
